language: python
python:
  - "2.7"
  - "3.4"
env:
  - DJANGO=1.5.12
  - DJANGO=1.6.9
  - DJANGO=1.7.2
install:
  - pip install -q Django==$DJANGO
  - pip install coveralls
script:
  - coverage run --source=hunger setup.py test
after_success:
  - coveralls
matrix:
  exclude:
    - python: "3.4"
      env: DJANGO=1.5.12
